version: "3"
services:
  nodeserverapp:
    build:
      context: ./app
    entrypoint: dockerize --wait tcp://db:3306 --timeout 20s docker-entrypoint.sh
    command: sh -c "yarn install && node index.js"
    networks:
      - node-network
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodeserverapp
      - MYSQL_ROOT_PASSWORD=senha@124
      - MYSQL_USER=userMysql
    networks:
      - node-network

  nginx:
    restart: always
    build:
      context: ./nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - nodeserverapp
    
networks:
  node-network:
    driver: bridge
